language: python

python:
  - 2.7
  - 3.5
  - 3.6

env:
  global:
    - MOZ_HEADLESS=1

before_install:
    - wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
    - mkdir geckodriver
    - tar -xzf geckodriver-v0.26.0-linux64.tar.gz -C geckodriver
    - export PATH=$PATH:$(pwd)/geckodriver
    - pip install -U pip

install:
  - pip install -r test-requirements.txt
  - pip install -r $VIRTUAL_ENV/src/xblock-sdk/requirements/base.txt
  - pip install -r $VIRTUAL_ENV/src/xblock-sdk/requirements/test.txt
  - pip install -r $VIRTUAL_ENV/src/xblock/requirements/base.txt
  - pip install -r $VIRTUAL_ENV/src/xblock/requirements/test.txt

script:
  - pycodestyle --max-line-length=100 activetable
  - pylint activetable
  - coverage run ./run_tests.py

notifications:
  email: false

addons:
  firefox: latest
